name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    name: Publicar no npm
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Instalar dependências
        run: npm ci

      - name: Executar lint & testes
        run: npm validate

      - name: Build
        run: npm run build

      - name: Publicar no npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
