name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    name: Publicar no npm
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Instalar dependências
        run: npm ci

      - name: Executar testes
        run: npm test

      - name: Build
        run: npm run build

      - name: Publicar no npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # - name: Criar Release no GitHub
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     generate_release_notes: true
      #     files: |
      #       ./dist/**/*
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}