name: RELEASE

on:
  push:
    tags:
      - v*.*.*

permissions:
  contents: write

jobs:
  publish:
    name: 🚀 Publicação no npm
    runs-on: ubuntu-22.04

    steps:
      - name: faz checkout do código
        uses: actions/checkout@v4

      - name: configura Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: https://registry.npmjs.org
          cache: npm

      - name: instala as dependências
        run: npm ci

      - name: valida o código
        run: |
          npm run check:types
          npm run lint
          npm run test

      - name: publica no npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}